# AUTOGENERATED! DO NOT EDIT! File to edit: Testing Page.ipynb (unless otherwise specified).

__all__ = ['hello_world']

# Cell
#default_exp core
def hello_world(string):
    print(string)

hello_world("foobar")